// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotesApi.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotesApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20230907214319_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotesApi.Data.DataModel.NoteDataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            DateCreation = new DateTime(2023, 9, 7, 21, 43, 19, 473, DateTimeKind.Utc).AddTicks(190),
                            Title = "My first note"
                        },
                        new
                        {
                            Id = 2,
                            Body = "LoremLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque dignissim vehicula iaculis. Sed mattis dui eros, in accumsan tellus efficitur lacinia. Nulla mollis consequat orci quis consectetur.",
                            DateCreation = new DateTime(2023, 9, 7, 21, 43, 19, 473, DateTimeKind.Utc).AddTicks(240),
                            Title = "My first note"
                        },
                        new
                        {
                            Id = 3,
                            Body = "Sed vitae magna consequat, sollicitudin enim et, vehicula dui. Integer porta lectus nec facilisis eleifend. Cras fermentum tellus vel neque fermentum, quis pellentesque felis pretium. Donec erat turpis, euismod eu massa non, ornare eleifend justo. Cras et mauris eros. Duis dapibus sem ut ornare hendrerit. Duis ornare tempus massa sed aliquet.",
                            DateCreation = new DateTime(2023, 9, 7, 21, 43, 19, 473, DateTimeKind.Utc).AddTicks(240),
                            Title = "My first note"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
